### Numpy Lab

In [2]:
import numpy as np

In [26]:
num = [2,11,5,7]
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
l = [1,2,3,4,5]
new_l = np.array(l)
print(type(l))
print(type(new_l))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
A = np.array([[1,2],
              [3,4]])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


For the system: Ax = b

In [22]:
A = np.array([[3,1],
              [1,2]])
b = np.array([9,8])
x = np.linalg.solve(A,b)

print("Solurion x:", x)

Solurion x: [2. 3.]


In [27]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

C = np.dot(A,B)
print("A * B:\n", C)
print()

D = A @ B
print(D)

A * B:
 [[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [35]:
nums = [2,7,11,15,3,6]

def twoSum(nums: list[int], target: int) -> list[int]:
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                return [i,j]
print(twoSum(nums,9))

[0, 1]
