# Alternating List

Our overall goal in this section is the following.

**Goal**: Write a function which takes input `n` and as output returns the length `n` list `[3,8,3,8,...]`.

## Writing a Function that Returns a Constant List

Let's see our first attempt to define such function `f`.

In [1]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)

In [2]:
f(5)

The overall syntax is correct (especially the indentations), but it does not return anything. 

Why? Because we missed the `return` statement!

How about this one?

In [3]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
        return mylist

In [4]:
f(5)

[3]

We do correctly return something, but not what we want. Here we are forcing the `return` statement to occur **within** the for loop, so we actually exit the function during the first step in the for loop. Below is a correct example.

In [5]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    return mylist

In [6]:
f(5)

[3, 3, 3, 3, 3]

In [7]:
f(6)

[3, 3, 3, 3, 3, 3]

Although we gave different values to `n` in the above examples, that assignment is only happening locally within the function itself.  The value of `n` is not accessible to us outside of the function. As you can see:

In [8]:
n

NameError: name 'n' is not defined

Similarly, if we define `n` outside of the function (for example, `n = 100`), that does not have any influence on the `n` inside the definition of the function.  

Nor does the `n` inside of the function have any influence on the `n` that we have defined to be 100 outside of the function.

In [9]:
n = 100

In [10]:
f(4)

[3, 3, 3, 3]

In [11]:
n

100

## Alternating Function -- Version 1

Let's use our previous example (rename the function `f` to `const`) to create `[3,3,3,3,...]`.

In [12]:
def const(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    return mylist

In [13]:
const(5)

[3, 3, 3, 3, 3]

Once we have our function defined, we can directly use it in the following for-loop.

In [14]:
def alt1(n):
    mylist = const(n)
    return mylist

In [15]:
alt1(4)

[3, 3, 3, 3]

==================================================

_**<font color = blue>In-class Exercise 1</font>**_: Modify function `alt1` (input: `n`) so that it can provide `[3,8,3,8,...]` with the length of `n`. You can add a for-loop to change the value of the odd-indexed elements to `8`. (**Hint**: use `range(1,n,2)`.)

**Question**: why we change the odd-indexed elements, not the even-indexed elements?

In [2]:
# write your code below
def alt1(n):
    lst = [3 for _ in range(0,n)]
    for i in range(1,n,2):
        lst[i] = 8
    return lst
        

==================================================

In [3]:
alt1(10)

[3, 8, 3, 8, 3, 8, 3, 8, 3, 8]

In [4]:
alt1(11)

[3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3]

## Alternating List - Version 2

The basic logic of the **Version 1**:
* Create `[3,3,3,3,...]`.
* Change the value of the odd-indexed elements to `8`.

Here we'll write a different version of the function, which will use an `if` statement to check if the index is even or odd. The basic logic of the **Version 2**: 
* If the element's index is even, then this element is `3`. Otherwise, it is `8`.

**Question**: how to check if a number is even or odd? We can use `m%n` to check the remainder of `m` divded by `n`.

In [19]:
i = 7

In [20]:
i%2

1

In [21]:
6%2

0

We can check if an integer `i` is even by checking `i%2 == 0`.  We use an `if` statement, which works very similarly to in MATLAB.

In [22]:
def alt2(n):
    mylist = [] # create an empty list
    for i in range(n):
        if i%2 == 0: # check if i can be divided by 2
            mylist.append(3) # if so, the i-th element is 3
        else:
            mylist.append(8)
    return mylist

In [23]:
alt2(5)

[3, 8, 3, 8, 3]

In [24]:
alt2(6)

[3, 8, 3, 8, 3, 8]

Here is a very similar version, where instead of `else` we use `elif`.  When using `elif`, you need to specify a condition.  

You can have as many `elif` statements as you want, although in this case, `i%2 == 0` and `i%2 == 1` exhaust all the possibilities, so in this case, no later `elif` statements (nor `else` statements) would ever be reached.

In [25]:
def alt2(n):
    mylist = []
    for i in range(n):
        if i%2 == 0:
            mylist.append(3)
        elif i%2 == 1:
            mylist.append(8)
    return mylist

In [26]:
alt2(5)

[3, 8, 3, 8, 3]

In [27]:
alt2(6)

[3, 8, 3, 8, 3, 8]

## Alternating List - Version 3 (Using NumPy)

NumPy is one of the most important python libraries, and should remind you a lot of MATLAB. Let’s start by seeing how we can import it into this notebook.

In [1]:
import numpy as np

**Note**:
* `np` is a standard abbreviation, and you should not use anything else when importing numpy.
* If you get an error at this step, it means that NumPy is not installed on your computer.

Many parts of NumPy are very similar to MATLAB.  For example, NumPy has a `zeros` function, just like MATLAB.  We write `np.zeros` rather than just `zeros`, so that Python knows this function is defined in the NumPy library.

In [29]:
A = np.zeros((3,5))

In [30]:
type(A)

numpy.ndarray

`ndarray` -- a type defined in the NumPy library.  The "nd" portion stands for "n-dimensional".

In [31]:
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
A.shape # check the shape (no. of rows and no. of columns) of A

(3, 5)

In [33]:
# This is different from MATLAB !
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

The elements of this array are floating point numbers, not integers.

In [34]:
type(np.zeros(7)[0])

numpy.float64

In [35]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

What if we need them to be integers? We can use the `dtype` argument.

In [36]:
# Here we specify that the `dtype` should be 64-bit integers.
np.zeros(7,dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0], dtype=int64)

==================================================

_**<font color = blue>In-class Exercise 2</font>**_: Write a function `alt3`, which take `n` as the input, and create an array with the length of `n`, and all the elements are zeros (64-bit integers).

In [37]:
# write your code below


==================================================

In [38]:
alt3(8)

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

NumPy supports many types of elementwise operations, just like Matlab.

In [39]:
alt3(8)+3

array([3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

Most standard types defined in Python do not support this sort of elementwise operation.  For example, `list` does not.

In [40]:
mylist = [0,0,0]

In [41]:
mylist+3

TypeError: can only concatenate list (not "int") to list

==================================================

_**<font color = blue>In-class Exercise 3</font>**_: Modity the function `alt3` to create `[3,3,3,3,...]` with the length of `n`.

In [42]:
# write your code below


==================================================

In [43]:
alt3(5)

array([3, 3, 3, 3, 3], dtype=int64)

We now have a version of the alternating function that returns a NumPy array of all 3s.

Recall that `A[1::2]` can select the odd-indexed elements of `A`.

==================================================

_**<font color = blue>In-class Exercise 4</font>**_: Modity the function `alt3` to create `[3,8,3,8,...]` with the length of `n`.

In [44]:
# write your code below


==================================================

In [45]:
alt3(5)

array([3, 8, 3, 8, 3], dtype=int64)

In [46]:
alt3(6)

array([3, 8, 3, 8, 3, 8], dtype=int64)

In [47]:
mylist = [3,1,4,1,5,9] # create a python list

In [48]:
mylist[::2] # select the even-indexed elements

[3, 4, 5]

In [49]:
mylist[::2] = -17 # cannot directly modify their values! (But we can in the MATLAB)

TypeError: must assign iterable to extended slice

Here we convert `mylist` to a NumPy array.

In [50]:
#It is not that bad, we can if it is an NumPy array.
myarray = np.array(mylist)

In [51]:
myarray[::2] = -17

In [52]:
myarray

array([-17,   1, -17,   1, -17,   9])

**Question**: what if (just what if) I do not want to use NumPy? 

If you really want to make this assignment using `mylist`, you need the right-hand side to be the same length as the number of slots you are trying to fill in.  (So the NumPy version is much easier to use.)

In [53]:
mylist[::2] = [-17, -17, -17]

In [54]:
mylist

[-17, 1, -17, 1, -17, 9]

If you use the wrong number of terms on the right side, you will get an error.

In [55]:
mylist[::2] = [-17, -17]

ValueError: attempt to assign sequence of size 2 to extended slice of size 3

In [56]:
mylist[::2] = [-17, -17, -17, -17]

ValueError: attempt to assign sequence of size 4 to extended slice of size 3

## Timing different strategies

Recall we have `alt2` (uses list) and `alt3` (uses NumPy) to create `[3,8,3,8,...]`. 

In [57]:
alt3(10)

array([3, 8, 3, 8, 3, 8, 3, 8, 3, 8], dtype=int64)

In [58]:
alt2(10)

[3, 8, 3, 8, 3, 8, 3, 8, 3, 8]

Recall we can use `%%timeit` to time how long it takes a block of code to run.

In [59]:
%%timeit
alt3(10)

2.96 µs ± 87.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


We will now see a timing method that gives just the time, without all of the extra information given by `%%timeit`.

In [60]:
# come with python, no installation needed
import time 

In [61]:
time.time()

1696747596.8252923

**This is a very interesting number**: this gives how much time has elapsed since the beginning of (computer) time: January 1st, 1970.

Notice, I can use this function as a **timer**.

In [62]:
start = time.time()
alt3(10**5)
end = time.time()
t = end-start

In [63]:
t

0.000972747802734375

Use a while loop to find `n` that `alt3` takes more than 0.2 seconds to run.

In [64]:
t = 0
n = 100 
while t < 0.2:
    n = n*2 
    start = time.time()
    alt3(n)
    end = time.time()
    t = end-start

Here we check that the time really is bigger than 5.

In [65]:
t

0.20714831352233887

In [66]:
n

52428800

What if we use `alt2` function?

In [67]:
print(n)
start = time.time()
alt2(n)
end = time.time()
t = end-start
print(t)

52428800
9.113466739654541


What if we modity our `alt3` function, used for-loops instead of slicing in our NumPy function?

In [68]:
def alt3b(n):
    A = np.zeros(n, dtype=np.int64)+3
    for i in range(1,n,2):
        A[i] = 8
    return A

In [69]:
print(n)
start = time.time()
alt3b(n)
end = time.time()
t = end-start
print(t)

52428800
3.090710401535034


Using for-loops is very slow! Avoid them when you can :)

## Other useful links

Christopher's youtube video playlist: https://www.youtube.com/watch?v=w3HxawiC-7s&list=PLHfGN68wSbbIuSS-Y1Y5zYDPN59OaggpA